stages:
  - test
  - build image
  - trigger deploy
  - static scans
  - publish pages

variables:
  VAULT_ADDR: "http://vault.sit-ota.aws.in.here.com"
  SONAR_USER_HOME: $CI_PROJECT_DIR/.caches/sonar

test:
  stage: test
  image: advancedtelematic/gitlab-jobs:0.2.4
  script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 -J-Xmx1G -J-XX:ReservedCodeCacheSize=128m clean coverage "testOnly -- -u test_reports"
  artifacts:
    paths:
      - test_reports
      - "target/scala-*/scoverage-data"
      - "target/scala-*/src_managed"
    reports:
      junit: test_reports/*.xml
  cache:
    paths:
      - .ivy2/
      - .sbt/

code coverage:
  extends: .report_scala_coverage
  image: advancedtelematic/gitlab-jobs:0.2.4

build docker image:
  stage: build image
  except:
    refs:
      - schedules
      - deploy/sit
  only:
    refs:
      - master
      - /^deploy/.*$/
  tags:
    - docker-sock
  image: advancedtelematic/gitlab-jobs:0.2.3
  script:
    - env | sort
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - sbt -x -sbt-dir ./.sbt -ivy ./.ivy2 -batch docker:publish -J-Xmx1G -J-XX:ReservedCodeCacheSize=128m -Dsbt.log.noformat=true
  cache:
    paths:
      - .ivy2/
      - .sbt/

trigger dev deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - master
  variables:
    ENV: "dev"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: web-events
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

trigger sit deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - deploy/sit
  variables:
    ENV: "sit"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: web-events
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master


include:
  - project: olp/edge/ota/infra/security
    ref: v0.0.5
    file: /shared.yaml
