stages:
  - test
  - build image
  - trigger deploy
  - prepare veracode scan
  - submit veracode scan
  - perform deps scan
  - publish pages

variables:
  VAULT_ADDR: "http://vault.sit-ota.aws.in.here.com"

test:
  stage: test
  extends: .report_scala_coverage
  tags:
    - docker-sock
  image: advancedtelematic/gitlab-jobs:0.2.3
  script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 -J-Xmx1G -J-XX:MaxPermSize=256m -J-XX:ReservedCodeCacheSize=128m clean coverage test
  cache:
    paths:
      - .ivy2/
      - .sbt/

build docker image:
  stage: build image
  except:
    refs:
      - schedules
      - deploy/sit
  only:
    refs:
      - master
      - /^deploy/.*$/
  tags:
    - docker-sock
  image: advancedtelematic/gitlab-jobs:0.2.3
  script:
    - env | sort
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - sbt -x -sbt-dir ./.sbt -ivy ./.ivy2 -batch docker:publish -J-Xmx1G -J-XX:MaxPermSize=256m -J-XX:ReservedCodeCacheSize=128m -Dsbt.log.noformat=true
  cache:
    paths:
      - .ivy2/
      - .sbt/

trigger dev deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - master
  variables:
    ENV: "dev"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: web-events
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

trigger sit deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - deploy/sit
  variables:
    ENV: "sit"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: web-events
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master


include:
  - project: olp/edge/ota/infra/security
    file: /shared.yaml
